### ISSUE TITLE
Crash with unbound armor (1.7.10 v3.0a)

### ISSUE THREAD

**Issue by Totoshe** [taji34/Troncraft#3]
I had a crash when i try to put armor :

workflow :
- create creative world
- get armor from inventory
- set gamemode to survival
- right click on helmet show unbound error message
- open inventory
- shift click on helmet (CRASH HERE)

I try the same workflow but i bound helmet before last step and it works. It append with other armor pieces.

java.lang.NullPointerException: Unexpected error
    at com.taji34.troncraft.items.EnerginiumArmorHelmet.getDamageReductionAmount(EnerginiumArmorHelmet.java:121)
    at com.taji34.troncraft.items.EnerginiumArmorHelmet.getArmorDisplay(EnerginiumArmorHelmet.java:170)
    at net.minecraftforge.common.ForgeHooks.getTotalArmorValue(ForgeHooks.java:198)
    at net.minecraftforge.client.GuiIngameForge.renderArmor(GuiIngameForge.java:269)
    at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:136)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by welnanick** [comment]
Code base restructure, issue no longer relevant.
